version: '3'

services:
  telegram-bot-api:
    container_name: telegram-bot-api
    image: "aiogram/telegram-bot-api:latest"
    environment:
      TELEGRAM_API_ID: "APP_ID"
      TELEGRAM_API_HASH: "APP_HASH"
      TELEGRAM_LOCAL: 1
    volumes:
      - ./telegram-bot-api:/var/lib/telegram-bot-api
    ports:
      - 8081:8081
  tgbot:
    container_name: hbcao1bot
    build: .
    command: python3 /tgbot/main.py hbcao1bot
    network_mode: "host"
    volumes:
      - .:/tgbot
    stop_signal: SIGINT
  