# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Locale.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cLocale.proto\"\x8f\x01\n\x06Locale\x12\"\n\x07\x63Locale\x18\x01 \x01(\x0b\x32\x11.Locale.LocaleIds\x12\"\n\x07sLocale\x18\x02 \x01(\x0b\x32\x11.Locale.LocaleIds\x1a=\n\tLocaleIds\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0e\n\x06script\x18\x02 \x01(\t\x12\x0e\n\x06region\x18\x03 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Locale_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOCALE']._serialized_start=17
  _globals['_LOCALE']._serialized_end=160
  _globals['_LOCALE_LOCALEIDS']._serialized_start=99
  _globals['_LOCALE_LOCALEIDS']._serialized_end=160
# @@protoc_insertion_point(module_scope)
