# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Restriction.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11Restriction.proto\"\x9a\x01\n\x0bRestriction\x12\x15\n\rteenagersMode\x18\x01 \x01(\x08\x12\x13\n\x0blessonsMode\x18\x02 \x01(\x08\x12\x1f\n\x04mode\x18\x03 \x01(\x0e\x32\x11.Restriction.Mode\x12\x0e\n\x06review\x18\x04 \x01(\x08\".\n\x04Mode\x12\n\n\x06NORMAL\x10\x00\x12\r\n\tTEENAGERS\x10\x01\x12\x0b\n\x07LESSONS\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Restriction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESTRICTION']._serialized_start=22
  _globals['_RESTRICTION']._serialized_end=176
  _globals['_RESTRICTION_MODE']._serialized_start=130
  _globals['_RESTRICTION_MODE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
